Repository rerun-io/egui_table, pull requests merged in 2024-09, with the labels that each got.

#1 Add `SplitScroll`
  Cargo.lock
  Cargo.toml
  demo/src/app.rs
  demo/src/lib.rs
  demo/src/main.rs
  demo/src/plot_demo.rs
  demo/src/split_scroll_demo.rs
  egui_table/src/lib.rs
  egui_table/src/split_scroll.rs
Labels: enhancement, include in changelog

#2 Add basic `Table`
  .vscode/launch.json
  Cargo.lock
  Cargo.toml
  demo/src/app.rs
  demo/src/lib.rs
  demo/src/table_demo.rs
  egui_table/Cargo.toml
  egui_table/src/columns.rs
  egui_table/src/lib.rs
  egui_table/src/split_scroll.rs
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#3 Improve `Table` to be almost usable
  Cargo.lock
  Cargo.toml
  README.md
  demo/src/main.rs
  demo/src/table_demo.rs
  egui_table/src/columns.rs
  egui_table/src/lib.rs
  egui_table/src/split_scroll.rs
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#6 More realistic demo with various fixes and tweaks
  Cargo.lock
  Cargo.toml
  README.md
  demo/src/table_demo.rs
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#7 Implement hierarchical table headers
  README.md
  demo/src/table_demo.rs
  egui_table/src/lib.rs
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#8 Provide visible column range to the prefetch function
  demo/src/table_demo.rs
  egui_table/src/lib.rs
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#9 Add `table.scroll_to_row(s)` and `scroll_to_column(s)`
  demo/src/table_demo.rs
  egui_table/src/split_scroll.rs
  egui_table/src/table.rs
Labels: include in changelog

#10 Make Column a builder
  demo/src/table_demo.rs
  egui_table/src/columns.rs
  egui_table/src/table.rs
Labels: include in changelog

#13 Support heterogenous row heights
  demo/src/table_demo.rs
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#14 Move `row_top_offset` to the `TableDelegate`
  demo/src/table_demo.rs
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#15 Always provide the table id to the delegate
  egui_table/src/table.rs
Labels: enhancement, include in changelog

#16 Fix rust workflows running twice in PR
  .github/workflows/links.yml
  .github/workflows/rust.yml
Labels: exclude from changelog
